import "@/styles/globals.css";
import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client";
import type { AppProps } from "next/app";
import dynamic from "next/dynamic";
import Head from "next/head";
import CountrieList from "./country/list";
import Country from "./country";


const client = new ApolloClient({
  uri: "http://localhost:4000",
  cache: new InMemoryCache({ addTypename: false }),
});


function App({ Component, pageProps }: AppProps) {
  // return <Component {...pageProps} />;
  return (
    <>
    
    <ApolloProvider client={client}>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
      </Head>

      <CountrieList />
      {/* <Country /> */}

    </ApolloProvider>

    </>
  )
}

// Disabling SSR
export default dynamic(() => Promise.resolve(App), { ssr: false });
